config/routes.rb
Rails.application.routes.draw do
  match '/admin/movies' => 'movies#create', via: :post
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  	get "movies/moviesbynav" 
  
  	devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }
    # as :user do
    #get 'login' => 'sessions#new', :as => "login"
    #get 'signup' => 'registrations#new', :as => "signup"  
    #get 'signout' => 'devise/sessions#destroy', :as => "signout"
#end
  	
	resources :movies do
		resources :reviews, except: [:show, :index]
  	end
  root 'movies#index'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :set_id, except:[:new,:create,:index,:show,:moviesbynav]


	def index
		
		search = params[:search]
	    if params[:search].present?
	      @movies = Movie.where("title like? OR title like? OR title like? OR title like?","%#{search.capitalize}%","%#{search.downcase}%","%#{search.upcase}%",
	      	"%#{search.titleize}%")
	    else
	      @movies = Movie.all
	    end

		@movies_sorted = @movies.order('rating DESC').limit(4)
    	@movies_viewed = @movies.order('impression_count DESC').limit(4)
    end

    def moviesbynav
    
    	search = params[:search]
		if params[:search].present?
	      @movies = Movie.where("title like? OR title like? OR title like? OR title like?","%#{search.capitalize}%","%#{search.downcase}%","%#{search.upcase}%",
	      	"%#{search.titleize}%")
	    else
	      @movies = Movie.all
	    end
		@movies_sorted = @movies.order('rating DESC')
    	@movies_viewed = @movies.order('impression_count DESC')

    end

	def create
		
		if params[:view] == "automatic"
			@call = AnotherServiceCall.new.api_call(params[:movie][:title])
			
			if @call == true
				redirect_to "#{ Rails.application.secrets.url}/admin/movies", notice: "Successfully Saved"
			else
				redirect_to new_admin_movie_path(view: params[:view]), alert: "No movie found"
			end
		else

			@movies =  Movie.new(movie_params)
			if @movies.save
			   redirect_to @movies,notice: "movie Successfully Saved"
			else
			   render 'new'
			end
		end
	end

	def show
		
		@movies1 = Movie.all
    	@movies = Movie.find(params[:id])
    	@i = Impression.create(movie_id: @movies.id)
		@movies_sorted = @movies1.order('rating DESC')
		

		if user_signed_in?
			@img = current_user.u_image_url
	    else
	    end
			@user = User.all

			@reviews = Review.where(movie_id: @movies.id).order("created_at DESC").limit(2)
			@reviews_for_modal = Review.where(movie_id: @movies.id).order("created_at DESC")
	end

	private
    def movie_params
    	
  	 	params.require(:movie).permit(:title,:image,:genre,:plot,:rating,:web, :year, :cast)
    end
 
  	def set_id
  		
   		@movies = Movie.find(params[:id])
  	end


end

app/helpers/movies_helper.rb
module MoviesHelper
	def imgcall(index)
		if index == 0
			return "active"
		else
		end
	end
end

app/views/movies/_form.html.erb
<%= form_for :movie, url: movies_path do |f| %>

 
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, id: :movie_title, class: "form-control ", required: true %>
    </div>


  <%if params[:view] == "automatic"%>
    <%= hidden_field_tag 'view', view %>
  <%else%>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, id: :movie_image, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :genre %>
      <%= f.text_field :genre, id: :movie_genre, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :plot %>
      <%= f.text_area :plot, id: :movie_plot, class: "form-control", required: true%>
    </div>

    <div class="form-group">
      <%= f.label :cast %>
      <%= f.text_area :cast, id: :movie_cast, class: "form-control", required: true%>
    </div>


    <div class="form-group">
      <%= f.label :year %>
      <%= f.date_field :year, id: :movie_year, as: :year %>
    </div>

    <div class="form-group">
      <%= f.label :rating %>
      <%= f.number_field :rating, id: :movie_rating, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :web %>
      <%= f.text_field :web, id: :movie_web, class: "form-control", required: true%>
  <%end%>
    </div>

    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
   <%end%>

app/views/movies/index.html.erb
<h1>BEST MOVIES</h1>
<div class="col-md-12">
	 <% if @movies.present? %>
	
	
				<div class="carousel slide" id="carousel-687387">
					<ol class="carousel-indicators">
						<li data-slide-to="0" data-target="#carousel-687387" class="active">
						</li>
						<li data-slide-to="1" data-target="#carousel-687387">
						</li>
						<li data-slide-to="2" data-target="#carousel-687387">
						</li>
					</ol>

					<div class="carousel-inner">
						<% @movies.order('id DESC').limit(3).each_with_index do |f, index| %>
						<div class="item <%= imgcall(index) %>">
								<a href= "<%= movie_path(f.id)%>" >
							<img style = "width: 300px; height: 400px; margin: 0px auto" alt="Carousel Bootstrap First" src="<%= f.image_url %>" class = "slider_custom" />
						</a>
							<div class="carousel-caption">
								<h4>
									First Thumbnail label
								</h4>

							</div>
						</div>
						<% end %>
					</div> <a class="left carousel-control" href="#carousel-687387" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-687387" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
				</div>
                <br>

                <div class="row">
					<div class = "col-md-12" >
						<h1> Top viewed movies </h1>
  							<% @movies_viewed.each do |movie| %>
    						<div class="col-sm-6 col-md-3">
      							<div class="thumbnail">
        							<a href= "<%= movie_path(movie.id)%>" >
        						 		<img style= "width: 300px;height: 400px;" src="<%= movie.image_url %>" class: 'image', movie %>
      						    	</a>
      							</div>
    						</div>
 					 		<% end %>
					</div>
					 	<div class="form-group">
      						<%= link_to "Browse More", movies_moviesbynav_path %>
  						</div>
				</div>

				<div class="row">
					<div class = "col-md-12" >
						<h1> Top rated movies </h1>
  							<% @movies_sorted.each do |movie| %>
    						<div class="col-sm-6 col-md-3">
      							<div class="thumbnail">
        							<a href= "<%= movie_path(movie.id)%>" >
        						 		<img style = "width: 300px;height: 400px;" src="<%= movie.image_url %>" class: 'image', movie %>
      						    	</a>
      							</div>
      							
    						</div>
 					 		<% end %>
					</div>
						<div class="form-group">
      						<%= link_to "Browse More", movies_moviesbynav_path %>
  						</div>
				</div>

     <% else %>
   		<div class="alert alert-warning" role="alert">
  			<strong>Warning!</strong> No movies found with this name, search again.
		</div>
	<%end%>
				
</div>

app/views/movies/moviesbynav.html.erb
<div class="col-md-12">

<div class="container">
 <h1>WATCH MOVIES BY VIEWS AND RATING</h1>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#byviews"><strong>By Views</strong></a></li>
    <li><a data-toggle="tab" href="#byrating"><strong>By Rating</strong></a></li>
  </ul>

  <div class="tab-content", style="float: left">
    <div id="byviews" class="tab-pane fade in active">
      <h3><strong>Top viewed movies</strong></h3>
        <% @movies_viewed.each do |movie| %>
						<div class="col-sm-6 col-md-3">
  							<div class="thumbnail">
    							<a href= "<%= movie_path(movie.id)%>" >
    						 		<img style= "width: 300px;height: 400px;" src="<%= movie.image_url %>" class: 'image', movie %>
  						    	</a>
  							</div>
						</div>
 				<% end %>
    </div>
    <div id="byrating" class="tab-pane fade">
      <h3><strong>Top rated movies</strong></h3>
    		<% @movies_sorted.each do |movie| %>
					<div class="col-sm-6 col-md-3">
							<div class="thumbnail">
  							<a href= "<%= movie_path(movie.id)%>" >
  						 		<img style = "width: 300px;height: 400px;" src="<%= movie.image_url %>" class: 'image', movie %>
						    </a>
							</div>
					</div>
			  <% end %>
    </div>
  </div>
</div>

                

				
</div>

app/views/movies/search.html.erb
<div class="row">
					<div class = "col-md-12" >
						<h1> Top viewed movies </h1>
  							<% @movies_sorted.each do |movie| %>
    						<div class="col-sm-6 col-md-3">
      							<div class="thumbnail">
        							<a href= "<%= movie_path(movie.id)%>" >
        						 		<img style= "width: 300px;height: 400px;" src="<%= movie.image_url %>" class: 'image', movie %>
      						    	</a>
      							</div>
    						</div>
 					 		<% end %>
					</div>
				</div>

				<div class="row">
					<div class = "col-md-12" >
						<h1> Top rated movies </h1>
  							<% @movies_sorted.each do |movie| %>
    						<div class="col-sm-6 col-md-3">
      							<div class="thumbnail">
        							<a href= "<%= movie_path(movie.id)%>" >
        						 		<img style = "width: 300px;height: 400px;" src="<%= movie.image_url %>" class: 'image', movie %>
      						    	</a>
      							</div>
      							
    						</div>
 					 		<% end %>
					</div>
				</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4 col-sm-4">
        <img style = "width: 300px;height: 400px;" alt="<% @movies.title %>" src="<%= @movies.image_url %>" class="img-thumbnail title-show" />
      </div>
         
        
        
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @movies.title + " " %> <%= image_tag 'rating.png' ,class: "rating-show-image"%><p class= "rating-show"> <%= @movies.rating %></p></td>
              </tr>
              <tr>
                <td><strong>Genre:</strong></td>
                <td><%= @movies.genre %></td>
              </tr>
              <tr>
                <td><strong>Plot:</strong></td>
                <td><%= @movies.plot %></td>
              </tr>
              
              <tr>
                <td><strong>Cast:</strong></td>
                <td><%= @movies.cast %></td>
              </tr>
              
            </tbody>
          </table>
        </div>
    </div>
  </div>
</div>
<div class = "col-md-12">
  
  <div class = "col-md-7 col-md-offset-1 well" >
     <h3>Reviews</h3>  
        <% if @reviews.blank? %>
          <h3>No reviews Would you like to add </h3>
        <% else %>
          <% @reviews.each do |review| %>
            <div class = "reviews" >
              <div class = "row" >

                <% @user.each do |usr| %>
                  <% if usr.id == review.user_id %>
                    <div class = "col-md-2 col-sm-2" >
                      <img style = "width: 100px;height: 50px;" src="<%= usr.u_image_url %>" class="img-thumbnail title-show" />
                    </div>
                    <p><strong><%= review.comment %></strong></p>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
          <br/>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">More review</button>
        <% end %>
        <h1>New Review</h1>
          <%= render partial:'reviews/form', locals: {reviews: @reviews} %>
  </div>
  
  <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <h4>Top 10 list of <%= @movies.genre%></h4>
            </h3>
          </div>
          <div class="panel-body table-responsive">
            
              <table class="table">
                
                <thead>
                  <tr>
                    <th>
                      ID
                    </th>
                    <th>
                      Name
                    </th>
                    <th>
                      Genre
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @movies_sorted.each do |movie| %>
                    <% if movie.genre == @movies.genre %>
                      <tr>
                        <td>
                           <%= movie.id %>
                        </td>
                        <td>
                          <a href= "<%= movie_path(movie.id)%>", style = "color:orange" >
                            <strong>
                              <%= movie.title %>
                            </strong>
                          </a>
                        </td>
                        <td>
                          <strong>
                            <%= movie.genre %>
                          </strong>
                        </td>
                      </tr>
                   
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            
          </div>
        </div>
      
  </div>
</div>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Reviews</h4>
        </div>
        <div class="modal-body">
          <% @reviews_for_modal.each do |review| %>
            <div class = "reviews" >
              <div class = "row">

                <% @user.each do |usr| %>

                  <% if usr.id == review.user_id %>
                    
                  
                    <div class = "col-md-2" >
                      <img style = "width: 100px;height: 50px;" src="<%= usr.u_image_url %>" class="img-thumbnail title-show" />
                    </div>
                    
                    <div class = "col-md-4">
                      <p><%= review.comment %></p>
                    </div>
                
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>



<script>
  $('.star-rating').raty({
    path: '/assets',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');

    }
  });
</script>